version: '3'
services:
  notebook:
    build:
      context: ./ops/tf-docker
    volumes:
        - ${PWD}:/home/jovyan/work
    ports:
      - "8888:8888"
    depends_on:
      - mlflow
    environment:
      MLFLOW_TRACKING_URI: 'http://mlflow:5000'
    command: "start-notebook.sh \
        --NotebookApp.disable_check_xsrf=True \
        --NotebookApp.allow_origin='https://colab.research.google.com'"
  mlflow:
    build:
      context: ./ops/mlflow-docker
    expose:
      - "5000"
    ports:
      - "5000:5000"
    depends_on:
      - postgres
  postgres:
    build:
      context: ./ops/postgres-docker
    restart: always
    environment:
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD: 'admin'
    ports: 
      - "5432:5432"
    volumes:
      - ./pg-data:/var/lib/postgresql/data
